#pragma once

#define GETBIT(VARIABLE,POSITION) ((VARIABLE) & (0x1ul << (POSITION)))

#define SETBIT(VARIABLE,POSITION) ((VARIABLE) |= (0x1ul << (POSITION)))
#define CLEARBIT(VARIABLE,POSITION) ((VARIABLE) &= ~(0x1ul << (POSITION)))
#define ASSIGNBIT(VARIABLE,POSITION,VALUE) ((VARIABLE) = ((VARIABLE) & ~(0x1ul << (POSITION))) | ((VALUE) << (POSITION)))